version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  quakelog-app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"

volumes:
  mongodata:
