name: Docker Build, Push and Update k8s

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: viniciusfca/quakelog:${{github.ref_name}}

    - name: Checkout k8s repo
      uses: actions/checkout@v2
      with:
        repository: viniciusfca/k8s
        token: ${{ secrets.TOKEN_GITHUB }}

    - name: Update k8s deployment file
      run: |
        cd quakelog
        ls
        sed -i 's|image:.*|image: viniciusfca/quakelog:${{github.ref_name}}|' quakelog.yaml

    - name: Commit and push changes
      run: |
        cd quakelog
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add quakelog.yaml
        git commit -m "Update image version"
        git push origin main
